name: Prepare Package
description: Executes the prepare_package function which prepares a database with the right
  package code for further downstream testing.

inputs:
  package-directory:
    description: "The directory where the package sources and tests are located."
    required: false
    default: ${{ github.workspace }}

  database-name:
    description: "The database name"
    required: true

  engine-name:
    description: "The name of the engine."
    required: true

runs:
  using: 'composite'
  steps:
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'

      - name: Build packages
        shell: bash
        run: |
          cd $GITHUB_ACTION_PATH/../../../
          julia --project=./ --color=yes  -e 'using Pkg; Pkg.build()'

      - name: Run prepare_package
        shell: bash
        id: prepare-package
        run: |
          cd $GITHUB_ACTION_PATH/../../../
          # Capture the output of the command in a variable
          ./rai-rel-test \
            --engine "${{ inputs.engine-name }}" \
            prepare_package "${{ inputs.package-directory }}" "${{ inputs.database-name }}"
