#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_DIR="$SCRIPT_DIR"


if [ "repl" == "$*" ]; then
    julia --project=$PROJECT_DIR --color=yes -i -e 'using Pkg; Pkg.instantiate(); using ReTestItems; using RAIRelTest'
else
    julia --project=$PROJECT_DIR --color=yes $PROJECT_DIR/main.jl $*
fi
