name: Test Package
description: Executes the test suites declared by a Rel package.

inputs:
  package-directory:
    required: true
    description: "The directory where the package sources and tests are located."

runs:
  using: 'composite'
  steps:
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'

      - name: Build packages
        shell: bash
        run: |
          cd $GITHUB_ACTION_PATH/../../../
          julia --project=./ --color=yes  -e 'using Pkg; Pkg.build()'

      - name: Run package tests
        shell: bash
        run: |
          cd $GITHUB_ACTION_PATH/../../../
          ./rai-rel-test --pool_size 2 test_package "${{ inputs.package-directory }}"
