name: Test Package
description: Executes the test suites declared by a Rel package.

inputs:
  package-directory:
    description: "The directory where the package sources and tests are located."
    required: false
    default: ${{ github.workspace }}

  pool-size:
    description: "The size of the engine pool to use."
    required: false
    default: 1

  changes:
    description: "Files that changed, to computed affected tests."
    required: false
    type: string
    default: ""

runs:
  using: 'composite'
  steps:
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'

      - name: Build packages
        shell: bash
        run: |
          cd $GITHUB_ACTION_PATH/../../../
          julia --project=./ --color=yes  -e 'using Pkg; Pkg.build()'

      - name: Run package tests
        shell: bash
        run: |
          CHANGES=${{ inputs.changes }}
          cd $GITHUB_ACTION_PATH/../../../
          ./rai-rel-test --pool_size ${{ inputs.pool-size }} test_package "${{ inputs.package-directory }}" --changes "$CHANGES"
